### ISSUE TITLE
Python3 for git-sync-deps

### ISSUE THREAD

**Issue by jaebaek** [google/amber#534]
When I use tools/git-sync-deps with python3, it shows the following error:

```
Traceback (most recent call last):
  File "tools/git-sync-deps", line 275, in <module>
    exit(main(sys.argv[1:]))
  File "tools/git-sync-deps", line 267, in main
    git_sync_deps(deps_file_path, argv, verbose)
  File "tools/git-sync-deps", line 212, in git_sync_deps
    deps_file = parse_file_to_dict(deps_file_path)
  File "tools/git-sync-deps", line 192, in parse_file_to_dict
    execfile(path, dictionary)
NameError: name 'execfile' is not defined
```

python2 works fine but I think we need to support python3.

**Comment by dj2** [comment]
Duplicate #528
