### ISSUE TITLE
SEGV on swiftshader for multiple_ssbo_update_with_graphics_pipeline.vkscript

### ISSUE THREAD

**Issue by dj2** [google/amber#725]
When running under swiftshader the multiple_ssbo_update_with_graphics_pipeline.vkscript test crashes.

`Thread 1 "amber" received signal SIGSEGV, Segmentation fault.`

```
#11 0x00007ffff0d75655 in std::unordered_map<VkDeviceMemory_T*, std::shared_ptr<ObjectUseData>, std::hash<VkDeviceMemory_T*>, std::equal_to<VkDeviceMemory_T*>, std::allocator<std::pair<VkDeviceMemory_T* const, std::shared_ptr<ObjectUseData> > > >::erase (this=0x555556abcbd0, __x=@0x7fffffffc970: 0x100000000010) at /usr/include/c++/8/bits/unordered_map.h:815
#12 0x00007ffff0d6a854 in vl_concurrent_unordered_map<VkDeviceMemory_T*, std::shared_ptr<ObjectUseData>, 6, std::hash<VkDeviceMemory_T*> >::erase (this=0x555556abc818, key=@0x7fffffffc970: 0x100000000010)
    at ../../third_party/vulkan-validationlayers/layers/vk_layer_utils.h:255
#13 0x00007ffff0d5a04e in counter<VkDeviceMemory_T*>::DestroyObject (this=0x555556abc800, object=0x100000000010) at ../../third_party/vulkan-validationlayers/layers/generated/thread_safety.h:139
#14 0x00007ffff0d50f6c in ThreadSafety::DestroyObject (this=0x555556a9af70, object=0x100000000010) at ../../third_party/vulkan-validationlayers/layers/generated/thread_safety.h:475
#15 0x00007ffff0d3fa7f in ThreadSafety::PostCallRecordFreeMemory (this=0x555556a9af70, device=0x555556731ec8, memory=0x100000000010, pAllocator=0x0)
    at ../../third_party/vulkan-validationlayers/layers/generated/thread_safety.cpp:749
#16 0x00007ffff09823a2 in vulkan_layer_chassis::FreeMemory (device=0x555556731ec8, memory=0x100000000010, pAllocator=0x0) at ../../third_party/vulkan-validationlayers/layers/generated/chassis.cpp:1259
#17 0x00007ffff7fc6b98 in vkFreeMemory (device=0x555556731ec8, mem=0x100000000010, pAllocator=0x0) at ../../third_party/vulkan-loader/loader/trampoline.c:887
#18 0x000055555625c9c8 in amber::vulkan::Device::<lambda(VkDevice, VkDeviceMemory, const VkAllocationCallbacks*)>::operator()(VkDevice, VkDeviceMemory, const VkAllocationCallbacks *) const (__closure=0x5555569b63e8, 
    device=0x555556731ec8, memory=0x100000000010, pAllocator=0x0) at ./vk-wrappers.inc:1798
#19 0x0000555556274625 in std::_Function_handler<void(VkDevice_T*, VkDeviceMemory_T*, const VkAllocationCallbacks*), amber::vulkan::Device::LoadVulkanPointers(PFN_vkGetInstanceProcAddr, amber::Delegate*)::<lambda(VkDevice, VkDeviceMemory, const VkAllocationCallbacks*)> >::_M_invoke(const std::_Any_data &, VkDevice_T *&&, VkDeviceMemory_T *&&, const VkAllocationCallbacks *&&) (__functor=..., __args#0=@0x7fffffffcb90: 0x555556731ec8, 
    __args#1=@0x7fffffffcb88: 0x100000000010, __args#2=@0x7fffffffcb80: 0x0) at /usr/include/c++/8/bits/std_function.h:297
#20 0x000055555624dd3a in std::function<void (VkDevice_T*, VkDeviceMemory_T*, VkAllocationCallbacks const*)>::operator()(VkDevice_T*, VkDeviceMemory_T*, VkAllocationCallbacks const*) const (this=0x5555569b63e8, 
    __args#0=0x555556731ec8, __args#1=0x100000000010, __args#2=0x0) at /usr/include/c++/8/bits/std_function.h:687
#21 0x000055555624d9e3 in amber::vulkan::TransferBuffer::~TransferBuffer (this=0x555556bec680, __in_chrg=<optimized out>) at ../../src/vulkan/transfer_buffer.cc:28
#22 0x000055555624da60 in amber::vulkan::TransferBuffer::~TransferBuffer (this=0x555556bec680, __in_chrg=<optimized out>) at ../../src/vulkan/transfer_buffer.cc:34
#23 0x0000555556242662 in std::default_delete<amber::vulkan::TransferBuffer>::operator() (this=0x555557041e78, __ptr=0x555556bec680) at /usr/include/c++/8/bits/unique_ptr.h:81
#24 0x00005555562426fb in std::unique_ptr<amber::vulkan::TransferBuffer, std::default_delete<amber::vulkan::TransferBuffer> >::reset (this=0x555557041e78, __p=0x555556bec680) at /usr/include/c++/8/bits/unique_ptr.h:382
#25 0x0000555556250005 in std::unique_ptr<amber::vulkan::TransferBuffer, std::default_delete<amber::vulkan::TransferBuffer> >::operator=(decltype(nullptr)) (this=0x555557041e78) at /usr/include/c++/8/bits/unique_ptr.h:318
#26 0x000055555624fe6a in amber::vulkan::BufferDescriptor::MoveResourceToBufferOutput (this=0x555557041e50) at ../../src/vulkan/buffer_descriptor.cc:65
#27 0x0000555556245231 in amber::vulkan::Pipeline::ReadbackDescriptorsToHostDataQueue (this=0x5555570c0650) at ../../src/vulkan/pipeline.cc:442
#28 0x000055555623ccc1 in amber::vulkan::GraphicsPipeline::Draw (this=0x5555570c0650, command=0x55555666f5c0, vertex_buffer=0x555556beff10) at ../../src/vulkan/graphics_pipeline.cc:919
#29 0x00005555562302b6 in amber::vulkan::EngineVulkan::DoDrawArrays (this=0x555556a7dbd0, command=0x55555666f5c0) at ../../src/vulkan/engine_vulkan.cc:458
#30 0x0000555555cd03fc in amber::Executor::ExecuteCommand (this=0x7fffffffd47f, engine=0x555556a7dbd0, cmd=0x55555666f5c0) at ../../src/executor.cc:146
#31 0x0000555555ccfe5b in amber::Executor::Execute (this=0x7fffffffd47f, engine=0x555556a7dbd0, script=0x5555566692d0, shader_map=std::map with 0 elements, options=0x7fffffffd9e0) at ../../src/executor.cc:90
#32 0x0000555555c95694 in amber::Amber::ExecuteWithShaderData (this=0x7fffffffd85f, recipe=0x555556669290, opts=0x7fffffffd9e0, shader_data=std::map with 0 elements) at ../../src/amber.cc:173
#33 0x0000555555c95565 in amber::Amber::Execute (this=0x7fffffffd85f, recipe=0x555556669290, opts=0x7fffffffd9e0) at ../../src/amber.cc:158
#34 0x0000555555c7fef3 in main (argc=2, argv=0x7fffffffe0e8) at ../../samples/amber.cc:475
```

**Comment by dj2** [comment]
`tests/cases/multiple_ssbo_with_sparse_descriptor_set_in_compute_pipeline_less_than_4.vkscript` crashes in a similar area of the code and maybe related ...

```
#4  0x00007ffff0d75390 in vl_concurrent_unordered_map<VkDeviceMemory_T*, std::shared_ptr<ObjectUseData>, 6, std::hash<VkDeviceMemory_T*> >::contains (this=0x555556abbae8, key=@0x7fffffffc878: 0x60000000006)
    at ../../third_party/vulkan-validationlayers/layers/vk_layer_utils.h:261
#5  0x00007ffff0d6a508 in counter<VkDeviceMemory_T*>::FindObject (this=0x555556abbad0, object=0x60000000006) at ../../third_party/vulkan-validationlayers/layers/generated/thread_safety.h:144
#6  0x00007ffff0d59817 in counter<VkDeviceMemory_T*>::StartWrite (this=0x555556abbad0, object=0x60000000006) at ../../third_party/vulkan-validationlayers/layers/generated/thread_safety.h:164
#7  0x00007ffff0d50e86 in ThreadSafety::StartWriteObject (this=0x555556a9a240, object=0x60000000006) at ../../third_party/vulkan-validationlayers/layers/generated/thread_safety.h:475
#8  0x00007ffff0d3fb50 in ThreadSafety::PreCallRecordUnmapMemory (this=0x555556a9a240, device=0x555556730da8, memory=0x60000000006) at ../../third_party/vulkan-validationlayers/layers/generated/thread_safety.cpp:782
#9  0x00007ffff09829dc in vulkan_layer_chassis::UnmapMemory (device=0x555556730da8, memory=0x60000000006) at ../../third_party/vulkan-validationlayers/layers/generated/chassis.cpp:1301
#10 0x00007ffff7fc6c27 in vkUnmapMemory (device=0x555556730da8, mem=0x60000000006) at ../../third_party/vulkan-loader/loader/trampoline.c:904
#11 0x000055555625e603 in amber::vulkan::Device::<lambda(VkDevice, VkDeviceMemory)>::operator()(VkDevice, VkDeviceMemory) const (__closure=0x5555569b55b8, device=0x555556730da8, memory=0x60000000006) at ./vk-wrappers.inc:2138
#12 0x0000555556275d53 in std::_Function_handler<void(VkDevice_T*, VkDeviceMemory_T*), amber::vulkan::Device::LoadVulkanPointers(PFN_vkGetInstanceProcAddr, amber::Delegate*)::<lambda(VkDevice, VkDeviceMemory)> >::_M_invoke(const std::_Any_data &, VkDevice_T *&&, VkDeviceMemory_T *&&) (__functor=..., __args#0=@0x7fffffffcbf0: 0x555556730da8, __args#1=@0x7fffffffcbe8: 0x60000000006) at /usr/include/c++/8/bits/std_function.h:297
#13 0x0000555556289e97 in std::function<void (VkDevice_T*, VkDeviceMemory_T*)>::operator()(VkDevice_T*, VkDeviceMemory_T*) const (this=0x5555569b55b8, __args#0=0x555556730da8, __args#1=0x60000000006)
    at /usr/include/c++/8/bits/std_function.h:687
#14 0x0000555556289a09 in amber::vulkan::Resource::UnMapMemory (this=0x555556bec080, memory=0x60000000006) at ../../src/vulkan/resource.cc:166
#15 0x000055555624d9a1 in amber::vulkan::TransferBuffer::~TransferBuffer (this=0x555556bec080, __in_chrg=<optimized out>) at ../../src/vulkan/transfer_buffer.cc:27
#16 0x000055555624da60 in amber::vulkan::TransferBuffer::~TransferBuffer (this=0x555556bec080, __in_chrg=<optimized out>) at ../../src/vulkan/transfer_buffer.cc:34
#17 0x0000555556242662 in std::default_delete<amber::vulkan::TransferBuffer>::operator() (this=0x5555570a3898, __ptr=0x555556bec080) at /usr/include/c++/8/bits/unique_ptr.h:81
#18 0x00005555562426fb in std::unique_ptr<amber::vulkan::TransferBuffer, std::default_delete<amber::vulkan::TransferBuffer> >::reset (this=0x5555570a3898, __p=0x555556bec080) at /usr/include/c++/8/bits/unique_ptr.h:382
#19 0x0000555556250005 in std::unique_ptr<amber::vulkan::TransferBuffer, std::default_delete<amber::vulkan::TransferBuffer> >::operator=(decltype(nullptr)) (this=0x5555570a3898) at /usr/include/c++/8/bits/unique_ptr.h:318
#20 0x000055555624fe6a in amber::vulkan::BufferDescriptor::MoveResourceToBufferOutput (this=0x5555570a3870) at ../../src/vulkan/buffer_descriptor.cc:65
#21 0x0000555556245231 in amber::vulkan::Pipeline::ReadbackDescriptorsToHostDataQueue (this=0x555556bee980) at ../../src/vulkan/pipeline.cc:442
#22 0x00005555562520ec in amber::vulkan::ComputePipeline::Compute (this=0x555556bee980, x=4, y=1, z=1) at ../../src/vulkan/compute_pipeline.cc:108
#23 0x00005555562303c6 in amber::vulkan::EngineVulkan::DoCompute (this=0x555556a7cfa0, command=0x55555666b200) at ../../src/vulkan/engine_vulkan.cc:467
#24 0x0000555555cd044d in amber::Executor::ExecuteCommand (this=0x7fffffffd45f, engine=0x555556a7cfa0, cmd=0x55555666b200) at ../../src/executor.cc:148
#25 0x0000555555ccfe5b in amber::Executor::Execute (this=0x7fffffffd45f, engine=0x555556a7cfa0, script=0x55555666a2d0, shader_map=std::map with 0 elements, options=0x7fffffffd9c0) at ../../src/executor.cc:90
#26 0x0000555555c95694 in amber::Amber::ExecuteWithShaderData (this=0x7fffffffd83f, recipe=0x55555666a290, opts=0x7fffffffd9c0, shader_data=std::map with 0 elements) at ../../src/amber.cc:173
#27 0x0000555555c95565 in amber::Amber::Execute (this=0x7fffffffd83f, recipe=0x55555666a290, opts=0x7fffffffd9c0) at ../../src/amber.cc:158
#28 0x0000555555c7fef3 in main (argc=2, argv=0x7fffffffe0c8) at ../../samples/amber.cc:475
```
