### ISSUE TITLE
ARMv7 (or ARMv6 os ARMhf) error

### ISSUE THREAD

**Issue by 0xD8C4A475** [google/amber#972]
Raspberry Pi 3:

```
root@raspberrypi:/home/pi/skia# python2 tools/git-sync-deps
Skipping "../src".
Skipping "bin".
...rd_party/externals/d3d12allocator @ 169895d529dfce00390a20e69c2f516066fe7a3b
...third_party/externals/libgifcodec @ fd59fa92a0c86788dcdd84d091e1ce81eda06a77
/home/pi/skia/buildtools             @ b138e6ce86ae843c42a1a08f37903207bebcca75
.../third_party/externals/markupsafe @ 0944e71f4b2cb9a871bcbe353f95e889b64a611a
...third_party/externals/swiftshader @ a4232c15e287a38b93d2a55bd1d7894cb4effac3
...skia/third_party/externals/jinja2 @ ee69aa00ee8536f61db6a451f3858745cf587de6
...hird_party/externals/egl-registry @ a0bca08de07c7d7651047bedc0b653cfaaa4f2ae
...i/skia/third_party/externals/zlib @ c876c8f87101c5a75f6014b0f832499afeb65b73
...i/skia/third_party/externals/piex @ bb217acdca1cc0c16b704669dd6f91a1b509c406
...ird_party/externals/spirv-headers @ 814e728b30ddd0f4509233099a3ad96fd4318c07
.../third_party/externals/abseil-cpp @ 789af048b388657987c59d4da406859034fe310f
.../skia/third_party/externals/wuffs @ 600cd96cf47788ee3a74b40a6028b035c9fd6a61
...kia/third_party/externals/libwebp @ 9ce5843dbabcfd3f7c39ec7ceba9cbeb213cbfdf
...kia/third_party/externals/dng_sdk @ c8d0c9b1d16bfda56f15165d39e0ffa360a11123
.../third_party/externals/microhttpd @ 748945ec6f1c67b7efc934ab0808e1d32f2fb98d
...d_party/externals/opengl-registry @ 14b80ebeab022b2c78f84a573f01028c96075553
...ird_party/externals/libjpeg-turbo @ 24e310554f07c0fdb8ee52e3e708e4f3e9eb6e20
...third_party/externals/spirv-tools @ 4b092d2ab81854e61632bdd1e658907f0071c37e
...third_party/externals/spirv-cross @ 0e2880ab990e79ce6cc8c79c219feda42d98b1e8
...ia/third_party/externals/freetype @ cff026d41599945498044d2f4dcc0e610ffb6929
...skia/third_party/externals/sfntly @ b55ff303ea2f9e26702b514cf6a3196a2e3e2974
...skia/third_party/externals/libpng @ 386707c6d19b974ca2e3db7f5c61873813c6fe44
.../skia/third_party/externals/expat @ a28238bdeebc087071777001245df1876a11f5ee
...i/skia/third_party/externals/tint @ 7dc901fa4f87c977ccd1f6ab652b6de0723a197a
.../skia/third_party/externals/imgui @ 55d35d8387c15bf0cfd71861df67af8cfbda7456
...skia/third_party/externals/brotli @ e61745a6b7add50d380cfd7d3883dd6c62fc2c71
...i/skia/third_party/externals/oboe @ b02a12d1dd821118763debec6b83d00a8a0ee419
...ia/third_party/externals/harfbuzz @ 3160789701463bcd822c26010da4de33c92c85d9
...i/skia/third_party/externals/dawn @ ef80b0908a1399b17cf7113a95423c91aa67cce8
...pi/skia/third_party/externals/icu @ a0718d4f121727e30b8d52c7a189ebf5ab52421f
...skia/third_party/externals/angle2 @ d4412d0a01247291a8357933c9c844cc55cb7490
Traceback (most recent call last):
  File "/home/pi/skia/bin/fetch-gn", line 26, in <module>
    cpu = {'amd64': 'amd64', 'arm64': 'arm64', 'x86_64': 'amd64'}[platform.machine().lower()]
KeyError: 'armv7l'
Traceback (most recent call last):
  File "/home/pi/skia/tools/git-sync-deps", line 269, in <module>
    exit(main(sys.argv[1:]))
  File "/home/pi/skia/tools/git-sync-deps", line 262, in main
    subprocess.check_call(
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', '/home/pi/skia/bin/fetch-gn']' returned non-zero exit status 1.

```
(same with python3)

**Comment by dneto0** [comment]
Is this really about amber? or is it the Skia project?

**Comment by dneto0** [comment]
Right, this doesn't look like the output of toot/git-sync-deps in this project.
